### ISSUE TITLE
Support for boolean operators

### ISSUE THREAD

**Issue by NickAger** [fivemoreminix/rsc#11]
Hi I noticed that you added initial support for boolean operators in this commit: https://github.com/fivemoreminix/rsc/commit/2b1ed6a032bb4394709c59a1236c6d8f776a8b32

It appears that in your version 3 rewrite this support was lost. Do you have plans to add support for boolean operations or did you find some blockers in the way the code is correctly structured? What would be the blockers in adding boolean operators into version 3?

Many thanks for a great library.

**Comment by fivemoreminix** [comment]
Hi, Nick. Many apologies for the ridiculous amount of time to respond. I had started a career in EMS around the time you sent the message and I was probably just so busy and ended up forgetting to answer your question.

It has been a few years since I started to implement booleans. I remember wondering if adding Boolean logic was what I wanted for the library. At one time I envisioned that RSC would be something like a secretly functional programming language hidden inside a calculator crate, but I think I scrapped it for simplicity.

Boolean conditions would be great for a lot of applications, so I'll definitely consider sitting down and implementing those. I've also wanted to make a v3.1 with a BigNum implementation so I'll likely do them together!

Thank you Nick for using my library, I hope I haven't frustrated you any way by taking so long.
